import type { EndpointDefinition } from "./types";

const apiDocsBase = "https://github.com/TechnitiumSoftware/DnsServer/blob/master/APIDOCS.md";

export const endpointCatalog: readonly EndpointDefinition[] = [
  {
    id: "user.login",
    category: "User",
    method: "GET",
    path: "/user/login",
    description: "Authenticate a user and return a session token.",
    docUrl: `${apiDocsBase}#login`,
    requiresToken: false,
    queryParams: [
      { name: "user", description: "Username", required: true },
      { name: "pass", description: "Password", required: true },
      { name: "totp", description: "One time password" },
      { name: "includeInfo", description: "Include server info", type: "boolean" },
    ],
  },
  {
    id: "user.logout",
    category: "User",
    method: "GET",
    path: "/user/logout",
    description: "Invalidate a session token.",
    docUrl: `${apiDocsBase}#logout`,
    requiresToken: true,
    queryParams: [{ name: "token", description: "Session token" }],
  },
  {
    id: "user.session.get",
    category: "User",
    method: "GET",
    path: "/user/session/get",
    description: "Get details about the current session.",
    docUrl: `${apiDocsBase}#get-session-info`,
    requiresToken: true,
  },
  {
    id: "user.session.delete",
    category: "User",
    method: "GET",
    path: "/user/session/delete",
    description: "Delete a session using its partial token.",
    docUrl: `${apiDocsBase}#delete-user-session`,
    requiresToken: true,
    queryParams: [{ name: "partialToken", description: "Partial token", required: true }],
  },
  {
    id: "user.profile.get",
    category: "User",
    method: "GET",
    path: "/user/profile/get",
    description: "Get profile details for the authenticated user.",
    docUrl: `${apiDocsBase}#get-user-profile-details`,
    requiresToken: true,
  },
  {
    id: "user.profile.set",
    category: "User",
    method: "GET",
    path: "/user/profile/set",
    description: "Update profile values for the authenticated user.",
    docUrl: `${apiDocsBase}#set-user-profile-details`,
    requiresToken: true,
    queryParams: [
      { name: "displayName", description: "Display name" },
      { name: "sessionTimeoutSeconds", description: "Session timeout (seconds)", type: "number" },
    ],
  },
  {
    id: "user.changePassword",
    category: "User",
    method: "GET",
    path: "/user/changePassword",
    description: "Change the password for the authenticated user.",
    docUrl: `${apiDocsBase}#change-password`,
    requiresToken: true,
    queryParams: [
      { name: "pass", description: "Current password", required: true },
      { name: "newPass", description: "New password", required: true },
      { name: "totp", description: "One time password" },
      { name: "iterations", description: "PBKDF2 iterations", type: "number" },
    ],
  },
  {
    id: "user.createToken",
    category: "User",
    method: "GET",
    path: "/user/createToken",
    description: "Create a non-expiring API token for a user.",
    docUrl: `${apiDocsBase}#create-api-token`,
    requiresToken: false,
    queryParams: [
      { name: "user", description: "Username", required: true },
      { name: "pass", description: "Password", required: true },
      { name: "tokenName", description: "Token label", required: true },
      { name: "totp", description: "One time password" },
    ],
  },
  {
    id: "dashboard.stats.get",
    category: "Dashboard",
    method: "GET",
    path: "/dashboard/stats/get",
    description: "Fetch dashboard statistics.",
    docUrl: `${apiDocsBase}#get-stats`,
    requiresToken: true,
    queryParams: [
      { name: "type", description: "Duration type" },
      { name: "utc", description: "Return UTC timestamps", type: "boolean" },
      { name: "node", description: "Cluster node" },
      { name: "start", description: "Custom start ISO timestamp" },
      { name: "end", description: "Custom end ISO timestamp" },
    ],
  },
  {
    id: "dashboard.stats.getTop",
    category: "Dashboard",
    method: "GET",
    path: "/dashboard/stats/getTop",
    description: "Fetch top dashboard statistics for a given type.",
    docUrl: `${apiDocsBase}#get-top-stats`,
    requiresToken: true,
    queryParams: [
      { name: "statsType", description: "Statistic category", required: true },
      { name: "type", description: "Duration type" },
      { name: "limit", description: "Result limit", type: "number" },
      { name: "node", description: "Cluster node" },
      { name: "start", description: "Custom start ISO timestamp" },
      { name: "end", description: "Custom end ISO timestamp" },
      { name: "noReverseLookup", description: "Disable reverse lookup", type: "boolean" },
      { name: "onlyRateLimitedClients", description: "Only rate limited clients", type: "boolean" },
    ],
  },
  {
    id: "dashboard.stats.deleteAll",
    category: "Dashboard",
    method: "GET",
    path: "/dashboard/stats/deleteAll",
    description: "Delete all dashboard statistics.",
    docUrl: `${apiDocsBase}#delete-all-stats`,
    requiresToken: true,
    queryParams: [{ name: "node", description: "Cluster node" }],
  },
  {
    id: "zones.list",
    category: "Zones",
    method: "GET",
    path: "/zones/list",
    description: "List authoritative zones on the server.",
    docUrl: `${apiDocsBase}#list-zones`,
    requiresToken: true,
    queryParams: [
      { name: "pageNumber", description: "Page number", type: "number" },
      { name: "zonesPerPage", description: "Zones per page", type: "number" },
      { name: "filter", description: "Name filter" },
      { name: "type", description: "Zone type" },
      { name: "includePermissions", description: "Include permissions", type: "boolean" },
      { name: "node", description: "Cluster node" },
    ],
  },
  {
    id: "zones.records.list",
    category: "Records",
    method: "GET",
    path: "/zones/records/list",
    description: "List DNS records for a domain within a zone.",
    docUrl: `${apiDocsBase}#list-records`,
    requiresToken: true,
    queryParams: [
      { name: "zone", description: "Zone name", required: true },
      { name: "domain", description: "Record domain", required: true },
      { name: "listZone", description: "List entire zone", type: "boolean" },
      { name: "node", description: "Cluster node" },
    ],
  },
  {
    id: "zones.records.add",
    category: "Records",
    method: "GET",
    path: "/zones/records/add",
    description: "Add a DNS record to a zone.",
    docUrl: `${apiDocsBase}#add-record`,
    requiresToken: true,
    queryParams: [
      { name: "zone", description: "Zone name", required: true },
      { name: "domain", description: "Record domain", required: true },
      { name: "type", description: "Record type", required: true },
      { name: "ttl", description: "Time to live", type: "number" },
      { name: "value", description: "Record value" },
      { name: "ipAddress", description: "IP address" },
      { name: "priority", description: "Record priority", type: "number" },
      { name: "weight", description: "Record weight", type: "number" },
      { name: "port", description: "Record port", type: "number" },
      { name: "target", description: "Target host" },
    ],
  },
  {
    id: "zones.records.update",
    category: "Records",
    method: "GET",
    path: "/zones/records/update",
    description: "Update an existing DNS record in a zone.",
    docUrl: `${apiDocsBase}#update-record`,
    requiresToken: true,
    queryParams: [
      { name: "zone", description: "Zone name", required: true },
      { name: "domain", description: "Record domain", required: true },
      { name: "type", description: "Record type", required: true },
      { name: "ttl", description: "Time to live", type: "number" },
      { name: "value", description: "Record value" },
      { name: "newValue", description: "Replacement value" },
      { name: "ipAddress", description: "IP address" },
      { name: "newIpAddress", description: "Replacement IP address" },
      { name: "priority", description: "Record priority", type: "number" },
      { name: "weight", description: "Record weight", type: "number" },
      { name: "port", description: "Record port", type: "number" },
      { name: "target", description: "Target host" },
    ],
  },
  {
    id: "zones.records.delete",
    category: "Records",
    method: "GET",
    path: "/zones/records/delete",
    description: "Delete a DNS record from a zone.",
    docUrl: `${apiDocsBase}#delete-record`,
    requiresToken: true,
    queryParams: [
      { name: "zone", description: "Zone name", required: true },
      { name: "domain", description: "Record domain", required: true },
      { name: "type", description: "Record type", required: true },
      { name: "value", description: "Record value" },
      { name: "ipAddress", description: "Record IP" },
      { name: "priority", description: "Record priority", type: "number" },
      { name: "weight", description: "Record weight", type: "number" },
      { name: "port", description: "Record port", type: "number" },
      { name: "target", description: "Target host" },
    ],
  },
  {
    id: "cache.list",
    category: "Cache",
    method: "GET",
    path: "/cache/list",
    description: "List cached zones and records.",
    docUrl: `${apiDocsBase}#list-cached-zones`,
    requiresToken: true,
    queryParams: [
      { name: "domain", description: "Domain name" },
      { name: "direction", description: "Browse direction" },
      { name: "node", description: "Cluster node" },
    ],
  },
  {
    id: "cache.delete",
    category: "Cache",
    method: "GET",
    path: "/cache/delete",
    description: "Delete cached entries for a domain.",
    docUrl: `${apiDocsBase}#delete-cached-zone`,
    requiresToken: true,
    queryParams: [
      { name: "domain", description: "Domain name", required: true },
      { name: "node", description: "Cluster node" },
    ],
  },
  {
    id: "cache.flush",
    category: "Cache",
    method: "GET",
    path: "/cache/flush",
    description: "Flush the entire DNS cache.",
    docUrl: `${apiDocsBase}#flush-dns-cache`,
    requiresToken: true,
    queryParams: [{ name: "node", description: "Cluster node" }],
  },
  {
    id: "allowed.list",
    category: "Allowed",
    method: "GET",
    path: "/allowed/list",
    description: "List allowed zones.",
    docUrl: `${apiDocsBase}#list-allowed-zones`,
    requiresToken: true,
    queryParams: [
      { name: "domain", description: "Domain name" },
      { name: "direction", description: "Browse direction" },
      { name: "node", description: "Cluster node" },
    ],
  },
  {
    id: "allowed.add",
    category: "Allowed",
    method: "GET",
    path: "/allowed/add",
    description: "Add a domain to the allowed list.",
    docUrl: `${apiDocsBase}#allow-zone`,
    requiresToken: true,
    queryParams: [{ name: "domain", description: "Domain name", required: true }],
  },
  {
    id: "allowed.delete",
    category: "Allowed",
    method: "GET",
    path: "/allowed/delete",
    description: "Remove a domain from the allowed list.",
    docUrl: `${apiDocsBase}#delete-allowed-zone`,
    requiresToken: true,
    queryParams: [{ name: "domain", description: "Domain name", required: true }],
  },
  {
    id: "blocked.list",
    category: "Blocked",
    method: "GET",
    path: "/blocked/list",
    description: "List blocked zones.",
    docUrl: `${apiDocsBase}#list-blocked-zones`,
    requiresToken: true,
    queryParams: [
      { name: "domain", description: "Domain name" },
      { name: "direction", description: "Browse direction" },
      { name: "node", description: "Cluster node" },
    ],
  },
  {
    id: "blocked.add",
    category: "Blocked",
    method: "GET",
    path: "/blocked/add",
    description: "Add a domain to the blocked list.",
    docUrl: `${apiDocsBase}#block-zone`,
    requiresToken: true,
    queryParams: [{ name: "domain", description: "Domain name", required: true }],
  },
  {
    id: "blocked.delete",
    category: "Blocked",
    method: "GET",
    path: "/blocked/delete",
    description: "Remove a domain from the blocked list.",
    docUrl: `${apiDocsBase}#delete-blocked-zone`,
    requiresToken: true,
    queryParams: [{ name: "domain", description: "Domain name", required: true }],
  },
  {
    id: "apps.list",
    category: "Apps",
    method: "GET",
    path: "/apps/list",
    description: "List installed DNS apps.",
    docUrl: `${apiDocsBase}#list-apps`,
    requiresToken: true,
    queryParams: [{ name: "node", description: "Cluster node" }],
  },
  {
    id: "apps.listStoreApps",
    category: "Apps",
    method: "GET",
    path: "/apps/listStoreApps",
    description: "List available apps from the store.",
    docUrl: `${apiDocsBase}#list-store-apps`,
    requiresToken: true,
    queryParams: [{ name: "node", description: "Cluster node" }],
  },
  {
    id: "apps.downloadAndInstall",
    category: "Apps",
    method: "GET",
    path: "/apps/downloadAndInstall",
    description: "Download and install a DNS app from a URL.",
    docUrl: `${apiDocsBase}#download-and-install-app`,
    requiresToken: true,
    queryParams: [
      { name: "name", description: "App name", required: true },
      { name: "url", description: "HTTPS zip URL", required: true },
    ],
  },
  {
    id: "settings.getDnsSettings",
    category: "Settings",
    method: "GET",
    path: "/settings/dns/get",
    description: "Retrieve DNS server settings.",
    docUrl: `${apiDocsBase}#get-dns-settings`,
    requiresToken: true,
  },
  {
    id: "settings.setDnsSettings",
    category: "Settings",
    method: "POST",
    path: "/settings/dns/set",
    description: "Update DNS server settings.",
    docUrl: `${apiDocsBase}#set-dns-settings`,
    requiresToken: true,
    notes: "Send settings as JSON in the request body or as query parameters.",
  },
  {
    id: "dns.resolve",
    category: "DnsClient",
    method: "GET",
    path: "/dns/client/resolve",
    description: "Resolve a DNS record using the server resolver.",
    docUrl: `${apiDocsBase}#resolve`,
    requiresToken: true,
    queryParams: [
      { name: "name", description: "Domain name", required: true },
      { name: "type", description: "Record type", required: true },
      { name: "class", description: "Record class" },
      { name: "resolver", description: "Resolver id" },
    ],
  },
  {
    id: "admin.sessions.list",
    category: "Administration",
    method: "GET",
    path: "/admin/sessions/list",
    description: "List active user sessions.",
    docUrl: `${apiDocsBase}#list-sessions`,
    requiresToken: true,
    queryParams: [{ name: "node", description: "Cluster node" }],
  },
  {
    id: "admin.users.list",
    category: "Administration",
    method: "GET",
    path: "/admin/users/list",
    description: "List users on the server.",
    docUrl: `${apiDocsBase}#list-users`,
    requiresToken: true,
    queryParams: [{ name: "node", description: "Cluster node" }],
  },
  {
    id: "logs.list",
    category: "Logs",
    method: "GET",
    path: "/logs/list",
    description: "List available log files.",
    docUrl: `${apiDocsBase}#list-logs`,
    requiresToken: true,
    queryParams: [{ name: "node", description: "Cluster node" }],
  },
  {
    id: "logs.download",
    category: "Logs",
    method: "GET",
    path: "/logs/download",
    description: "Download a log file.",
    docUrl: `${apiDocsBase}#download-log`,
    requiresToken: true,
    queryParams: [
      { name: "fileName", description: "Log file name", required: true },
      { name: "limit", description: "Size limit (MB)", type: "number" },
      { name: "node", description: "Cluster node" },
    ],
  },
  {
    id: "logs.delete",
    category: "Logs",
    method: "GET",
    path: "/logs/delete",
    description: "Delete a log file.",
    docUrl: `${apiDocsBase}#delete-log`,
    requiresToken: true,
    queryParams: [
      { name: "log", description: "Log file name", required: true },
      { name: "node", description: "Cluster node" },
    ],
  },
];

const endpointMap = new Map(endpointCatalog.map((endpoint) => [endpoint.id, endpoint]));

export function getEndpointDefinition(id: string): EndpointDefinition {
  const endpoint = endpointMap.get(id);
  if (!endpoint) {
    throw new Error(`Unknown Technitium endpoint: ${id}`);
  }
  return endpoint;
}

export function listEndpointIds(): string[] {
  return endpointCatalog.map((endpoint) => endpoint.id);
}
